# Generated by Django 2.0.7 on 2018-07-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='extras',
            field=models.ManyToManyField(blank=True, to='orders.Extra'),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
    ]
