# Generated by Django 2.0.7 on 2018-07-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180731_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='is_large',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_item',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
