# Generated by Django 2.0.7 on 2018-08-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_cart_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='is_large',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SH', 'Still Shopping'), ('PL', 'Placed'), ('CO', 'Complete')], default='SH', max_length=2),
        ),
        migrations.AddField(
            model_name='order_item',
            name='extras',
            field=models.ManyToManyField(blank=True, to='orders.Extra'),
        ),
        migrations.AddField(
            model_name='order_item',
            name='size',
            field=models.CharField(choices=[('SM', 'Small'), ('LG', 'Large'), ('NA', 'Not Applicable')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='order_item',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Cart_item',
        ),
    ]
